name: Test

on:
  push:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/actions/build
      - run: pnpm run test
